application: mega-mailman
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: backend.megamailman.api
  secure: always
- url: /css
  static_dir: frontend/static/css
- url: /js
  static_dir: frontend/static/js
- url: /img
  static_dir: frontend/static/img
# Catch all to display the frontend
- url: /.*
  script: frontend.index.app
  secure: always

libraries:
- name: webapp2
  version: latest
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest